name: Build and Push Docker Images

on:
  push:
    branches:
    - main

env:
  REGISTRY: docker.io
  IMAGE_PREFIX: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - app: catalogue
          context: ./catalogue
        - app: voting
          context: ./voting
        - app: frontend
          context: ./frontend
        - app: recommendation
          context: ./recommendation
          
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5.0.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.11.1

    - name: Login to Docker Hub
      uses: docker/login-action@v3.5.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6.18.0
      with:
        context: ${{ matrix.context }}
        file: ${{ matrix.context }}/Dockerfile
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.app }}:latest
          ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.app }}:${{ github.sha }}
        # Tries to restore Docker layer cache from previous builds
        cache-from: type=gha
        # Saves the Docker layer cache for future builds
        cache-to: type=gha, mode=max
        # GHA stands for GitHub Actions Cache
        
    

    
          



